apiVersion: v2
name: control-plane
description: A Helm chart for ArmoniK Control Plane

# Specify the Kubernetes version range that we support.
kubeVersion: ">=v1.23.0-0"
keywords:
  - armonik
  - helm
  - control-plane

type: application
version: 0.1.0
appVersion: "0.2.2"

# home: https://github.com/aneoconsulting/ArmoniK.Infra/tree/main/charts/armonik/charts/control-plane
# sources:
#   - https://github.com/aneoconsulting/ArmoniK.Infra/tree/main/charts/armonik/charts/control-plane

# Maintainers
maintainers:
  - name: Aneo
    email: armonik-support@aneo.fr
    url: armonik.fr
