openapi: "3.0.1"
info:
  title: "htc-cr-update-private"
  description: "Private API Gateway for HTC Grid"
  version: "2021-06-21T05:51:50Z"
servers:
  - url: "https://rv1n4bmm0k.execute-api.eu-west-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "/v1"
paths:
  /submit:
    post:
      summary: Submit tasks
      requestBody:
        description: Job submission to the grid
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostSubmitResponse'
      responses:
        200:
          description: ssful operationsuccessful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/PostSubmitResponse'
        542:
          description: Invalid status value
          content: { }
      security:
        - api_key: []
  /cancel:
    post:
      summary: Cancel tasks
      requestBody:
        description: Job cancellation to the grid
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        200:
          description: ssful operationsuccessful operation
          content:
            application/json:
              schema:
                type: string
        542:
          description: Invalid status value
          content: { }
      security:
        - api_key: []
  /result:
    post:
      summary: Get results
      requestBody:
        description: Job submission to the grid
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetResponse'
      responses:
        200:
          description: ssful operationsuccessful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GetResponse'
        542:
          description: Invalid status value
          content: { }
      security:
        - api_key: []
components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
  schemas:
    GetMetadataResponse:
      type: object
      properties:
        tasks_in_response:
          type: integer
          format: int64
    GetResponse:
      type: object
      properties:
        finished:
          type: array
          items:
            type: string
        finished_output:
          type: array
          items:
            type: string
        cancelled:
          type: array
          items:
            type: string
        cancelled_output:
          type: array
          items:
            type: string
        failed:
          type: array
          items:
            type: string
        failed_output:
          type: array
          items:
            type: string
        message:
          type: string
        metadata:
          $ref: '#/components/schemas/GetMetadataResponse'
    PostSubmitResponse:
      type: object
      properties:
        task_ids:
          type: array
          items:
            type: string
        session_id:
          type: string