apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "control-plane-configmap" .Values.config.controlPlane.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    component: "control"
data:
  {{- $defaultPartition := .Values.config.controlPlane.defaultPartition }}
  {{- $partitionNames := keys .Values.config.computePlane.partitions | default list }}

  {{- if and $defaultPartition (has $defaultPartition $partitionNames) }}
  Submitter__DefaultPartition: {{ $defaultPartition }}
  {{- else if gt (len $partitionNames) 0 }}
  Submitter__DefaultPartition: {{ index $partitionNames 0 }}
  {{- else }}
  Submitter__DefaultPartition: ""
  {{- end }}
  
  {{- range $key, $value := .Values.config.controlPlane.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{ $conf := include "armonik.conf.control" $ | fromYaml | include "armonik.conf.materialize" | fromYaml }}
  {{ with $conf }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
