{{- if and .Values.tls.enabled .Values.tls.certManager.enabled }}
{{- if not .Values.tls.certManager.existingIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
  name: {{ include "armonik.fullname" . }}-issuer
  namespace: {{ include "armonik.namespace" . }}
spec:
  selfSigned: {}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "armonik.fullname" . }}
  namespace: {{ include "armonik.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
spec:
  commonName: {{ include "armonik.fullname" . }}-cert
  dnsNames:
  - {{ include "armonik.fullname" . }}.{{ include "armonik.namespace" . }}
  - {{ include "armonik.fullname" . }}.{{ include "armonik.namespace" . }}.svc
  - {{ include "armonik.fullname" . }}.{{ include "armonik.namespace" . }}.svc.{{ .Values.tls.clusterDomain }}
  secretName: {{ include "armonik.fullname" . }}
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
  {{- with .Values.tls.certManager.duration }}
  duration: {{ . }}
  {{- end }}
  {{- with .Values.tls.certManager.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
  issuerRef:
    {{- if .Values.tls.certManager.existingIssuer.enabled }}
    name: {{ .Values.tls.certManager.existingIssuer.name }}
    kind: {{ .Values.tls.certManager.existingIssuer.kind }}
    {{- else }}
    name: {{ include "armonik.fullname" . }}-issuer
    kind: Issuer
    {{- end }}
    group: cert-manager.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "armonik.fullname" . }}-cert-manager-wait
  namespace: {{ include "armonik.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "armonik.fullname" . }}-cert-manager-wait
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "armonik.fullname" . }}-cert-manager-wait
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ include "armonik.fullname" . }}-cert-manager-wait
  namespace: {{ include "armonik.namespace" . }}

roleRef:
  kind: ClusterRole
  name: {{ include "armonik.fullname" . }}-cert-manager-wait
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "armonik.fullname" . }}-wait-cert-manager
  namespace: {{ include "armonik.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

spec:
  template:
    spec:
      restartPolicy: Never

      serviceAccountName: {{ include "armonik.fullname" . }}-cert-manager-wait

      containers:
      - name: wait
        image: bitnami/kubectl:latest
        command:
        - sh
        - -c
        - |
          set -e

          echo "Waiting for cert-manager webhook deployment..."

          kubectl wait \
            --for=condition=Available \
            deployment/cert-manager-webhook \
            -n {{ include "armonik.namespace" . }} \
            --timeout=300s


          echo "Waiting for webhook CA injection..."

          until kubectl get validatingwebhookconfiguration cert-manager-webhook \
            -o jsonpath='{.webhooks[0].clientConfig.caBundle}' | grep -q .;
          do
            echo "CA bundle not injected yet..."
            sleep 5
          done

          echo "cert-manager webhook ready"
{{- end }}
