{{- if (list .Values "networkPolicies" "dns" "enabled" | include "armonik.utils.index" | default false) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "armonik.fullname" . }}-kube-dns-egress
  namespace: {{ .Values.namespace | default (include "armonik.namespace" .) | quote }}
  labels:
    app.kubernetes.io/component: ingress
    {{- include "armonik.labels" . | nindent 4 }}
spec:
  podSelector:
    {{- toYaml .Values.networkPolicies.dns.podSelector | nindent 4 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicies.dns.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicies.dns.labels | nindent 14 }}
      ports:
        {{- toYaml .Values.networkPolicies.dns.ports | nindent 8 }}
{{- end }}