{{- $networkPolicyEnabled := list .Values "networkPolicy" "enabled"
    | include "armonik.utils.index"
    | default false
-}}

{{- if $networkPolicyEnabled }}

{{/*
  Ingress backend NetworkPolicy.
*/}}
{{- include "armonik.netpol.render" (dict
      "context" .
      "component" "ingress"
      "config" (include "armonik.netpol.ingressBackend" . | fromYaml)
  ) }}

{{/*
  Ingress GUI NetworkPolicy.
*/}}
{{- include "armonik.netpol.render" (dict
      "context" .
      "component" "gui"
      "config" (include "armonik.netpol.ingressGui" . | fromYaml)
  ) }}

{{- end }}
