apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage
    service: activemq
    type: queue
  name: activemq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: storage
      service: activemq
      type: queue
  template:
    metadata:
      labels:
        app: storage
        service: activemq
        type: queue
      name: activemq
    spec:
      containers:
      - image: symptoma/activemq:5.18.4
        imagePullPolicy: IfNotPresent
        name: activemq
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
        - containerPort: 8161
          name: dashboard
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: ACTIVEMQ_OPTS_MEMORY
            value: {{.Values.activemqOptsMemory }}
        {{- if .Values.resources }}
        resources:
        {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        # - mountPath: /credentials/
        #   mountPropagation: None
        #   name: activemq-storage-secret-volume
        #   readOnly: true
        - mountPath: /opt/activemq/conf/
          mountPropagation: None
          name: activemq-jetty-xml
          readOnly: true
        - mountPath: /opt/activemq/webapps/api/WEB-INF/classes/
          mountPropagation: None
          name: activemq-jolokia-xml
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      # - name: activemq-storage-secret-volume
      #   secret:
      #     defaultMode: 420
      #     optional: false
      #     secretName: activemq-crt
      - configMap:
          defaultMode: 420
          name: activemq-configs
          optional: false
        name: activemq-jetty-xml
      - configMap:
          defaultMode: 420
          name: activemq-jolokia-configs
          optional: false
        name: activemq-jolokia-xml
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
