apiVersion: v1
kind: Service
metadata:
  labels:
    app: storage
    service: activemq
    type: queue
  name: activemq
spec:
  ports:
  - name: amqp
    port: 5672
  - name: dashboard
    port: 8161
  selector:
    app: storage
    service: activemq
    type: queue
