{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "system:%s" (include "activemq.fullname" .) }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ template "activemq.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "activemq.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
