repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      #      - id: terraform_docs
      #        args:
      #          - '--args=--lockfile=false'
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
          - '--args=--only=terraform_unused_required_providers'
          - '--args=--only=terraform_empty_list_equality'
          - '--args=--only=terraform_module_version'
      - id: terraform_tfsec
#      - id: terraform_checkov
#        args:
#          - --args=--quiet
#          - --args=--skip-framework github_configuration github_actions
#          - --args=--download-external-modules true
#          - --args=--run-all-external-checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-json
#      - id: check-yaml
#        args: [ --allow-multiple-documents ]
      - id: end-of-file-fixer
        exclude: ".*md$"
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
