repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--lockfile=false
          - --args=--output-file=README.md
          - --args=--output-mode=inject
          - --args=--indent=2
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
          - '--args=--only=terraform_unused_required_providers'
          - '--args=--only=terraform_empty_list_equality'
          - '--args=--only=terraform_module_version'
      #- id: terraform_tfsec
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
        args: [ --allow-multiple-documents]
        exclude: charts/.*/template\.*
      - id: end-of-file-fixer
        exclude: ".*md$"
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
      - id: mixed-line-ending
        args:
          - "--fix=lf"
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts # Make the tool search for charts only under the `charts` directory
          - --template-files=./_templates.gotmpl # The `./` makes it relative to the chart-search-root set above
          - --template-files=README.md.gotmpl # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl] # A base filename makes it relative to each chart directory found
