name: 'Deploy ArmoniK Infra'
description: 'Action to deploy ArmoniK infra in current github workflow'
inputs:
  control-plane-image:
    description: 'Repository/image for control plane docker image'
    required: false
    default: 'None'
  control-plane-tag:
    description: 'Tag for control plane docker image'
    required: false
    default: 'None'
  polling-agent-image:
    description: 'Repository/image for polling agent docker image'
    required: false
    default: 'None'
  polling-agent-tag:
    description: 'Tag for polling agent docker image'
    required: false
    default: 'None'
  worker-image:
    description: 'Repository/image for worker docker image'
    required: false
    default: 'None'
  worker-tag:
    description: 'Tag for worker docker image'
    required: false
    default: 'None'
  docker-is-installed:
    description: 'Is docker installed ?'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release jq python3 python-is-python3 python3-pip
        pip install python-hcl2 jsonpath-ng

    - if: ${{ inputs.docker-is-installed != 'true' }}
      name: Install docker
      shell: bash
      run: |
        cd ${{ github.action_path }}
        sh tools/install/docker.sh

    - name: Install kubectl
      shell: bash
      run: |
        cd ${{ github.action_path }}
        sh tools/install/kubectl.sh

    - name: Install terraform
      shell: bash
      run: |
        cd ${{ github.action_path }}
        sh tools/install/terraform.sh

    - name: Install K3s
      shell: bash
      run: |
        cd ${{ github.action_path }}
        bash tools/install/k3s.sh

    - name: Set environement variables
      shell: bash
      run: |
        set -ex
        cd ${{ github.action_path }}/infrastructure/quick-deploy/localhost
        source envvars.sh

    - name: Create shared host path directory
      shell: bash
      run: |
        set -ex
        cd ${{ github.action_path }}
        sudo mkdir -p /data
        sudo chown -R $USER:$USER /data

    - name: Create Kubernetes namespace
      shell: bash
      run: |
        set -ex
        cd ${{ github.action_path }}/infrastructure/quick-deploy/localhost
        make create-namespace

    - name: Deploy storage
      shell: bash
      run: |
        set -ex
        cd ${{ github.action_path }}/infrastructure/quick-deploy/localhost
        make deploy-storage

    - name: Deploy monitoring
      shell: bash
      run: |
        set -ex
        cd ${{ github.action_path }}/infrastructure/quick-deploy/localhost
        make deploy-monitoring

    - name: Deploy ArmoniK
      shell: bash
      run: |
        set -ex
        cd ${{ github.action_path }}/infrastructure/quick-deploy/localhost
        make deploy-armonik

    - name: Copy logs
      if: always()
      shell: bash
      run: |
        set -e
        mkdir -p /tmp/armoniklogs
        sudo cp -rL /var/log/pods/armonik* /tmp/armoniklogs
        sudo chown $USER -R /tmp/armoniklogs
        find /tmp/armoniklogs -name "*.log"

    - name: Store logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Logs ArmoniK - ${{ github.job }}
        path: /tmp/armoniklogs/**/*.log
        retention-days: 5