{{- if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "armonik.fullname" . | printf "%s-lb-cluster-certs" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "armonik.namespace" . }}
  labels:
    app.kubernetes.io/component: load-balancer
    {{- include "armonik.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $cluster, $conf := .Values.loadBalancer.clusters }}
  {{- with $conf.certPem }}
  {{ printf "%s.cert" $cluster }}: {{ . | b64enc }}
  {{- end }}
  {{- with $conf.keyPem }}
  {{ printf "%s.key" $cluster }}: {{ . | b64enc }}
  {{- end }}
  {{- with $conf.caCert }}
  {{ printf "%s.ca" $cluster }}: {{ . | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
