apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cloudwatch-adapter
  namespace: custom-metrics
  labels: 
    app: k8s-cloudwatch-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cloudwatch-adapter
  template:
    metadata:
      labels:
        app: k8s-cloudwatch-adapter
    spec:
      serviceAccountName: k8s-cloudwatch-adapter
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - /adapter
          - --cert-dir=/tmp
          - --secure-port=6443
          - --logtostderr=true
          - --v=10
          ports:
          - containerPort: 6443
            name: https
          - containerPort: 8080
            name: http
          volumeMounts:
          - mountPath: /tmp
            name: temp-vol
      volumes:
      - name: temp-vol
        emptyDir: {}  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
