global:
  imageRegistry: ""
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent
nameOverride: "activemq"
replicaCount: 1
activemqOptsMemory: "-Xms1g -Xmx1g"
certificates:
  enable: false
image:
  repository: symptoma
  name: activemq
  tag: "5.18.4"
  pullPolicy: IfNotPresent
  imagePullSecrets: []
  registry: ""
