{{- if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "armonik.fullname" . | printf "%s-load-balancer" | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ include "armonik.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: load-balancer
    {{- include "armonik.labels" . | nindent 4 }}
  {{- with coalesce .Values.loadBalancer.service.annotations .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if eq .Values.loadBalancer.service.type "HeadLess" }}
  type: "ClusterIP"
  clusterIP: "None"
{{ else }}
  type: {{ .Values.loadBalancer.service.type | quote }}
{{- end }}
  selector:
    app.kubernetes.io/component: load-balancer
    {{- include "armonik.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ eq .Values.loadBalancer.service.type "HeadLess" | ternary .Values.loadBalancer.conf.listenPort .Values.loadBalancer.service.port }}
      targetPort: {{ .Values.loadBalancer.conf.listenPort }}
      protocol: TCP
      appProtocol: kubernetes.io/h2c
{{- end }}
