{{ if .Values.controlPlanConfigmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ first .Values.configmaps }}
  namespace: {{ .Values.namespace }}
data:
{{ if or (not .Values.defaultPartition) (eq .Values.defaultPartition "") (not (has .Values.defaultPartition .Values.partitionNames ))}}
  {{ if gt (len .Values.partitionNames) 0 }}
  Submitter__DefaultPartition: {{ first .Values.partitionNames }}
  {{ else }}
  Submitter__DefaultPartition: ""
  {{ end }} 
{{ else }}  
  Submitter__DefaultPartition: {{ .Values.defaultPartition }}
{{ end}}
{{ toYaml .Values.extraConf.control | indent 2 }}
{{ end }}
