apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.controlPlane.name }}
data:
  {{- $defaultPartition := .Values.config.controlPlane.defaultPartition }}
  {{- $partitionNames := keys .Values.config.computePlane.partitions | default list }}

  {{- if and $defaultPartition (has $defaultPartition $partitionNames) }}
  Submitter__DefaultPartition: {{ $defaultPartition }}
  {{- else if gt (len $partitionNames) 0 }}
  Submitter__DefaultPartition: {{ index $partitionNames 0 }}
  {{- else }}
  Submitter__DefaultPartition: ""
  {{- end }}

  {{- range $key, $value := .Values.config.controlPlane.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

