apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labelsApp | default "armonik" | quote }}
    service: {{ .Values.labelsService | default "control-plane" | quote }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}spec:
{{ if eq .Values.serviceType "HeadLess" }}
  type: "ClusterIP"
  clusterIP: "None"
{{ else }}
  type: .Values.serviceType
  clusterIP: null
{{ end }}
  selector:
    app: {{ .Values.labelsApp | default "armonik" | quote }}
    service: {{ .Values.labelsService | default "control-plane" | quote }}
  ports:
    - name: {{ .Values.namePort }}
    {{ if (eq .Values.serviceType "HeadLess") }}
      port: {{ .Values.containerPort }}
    {{ else }}
      port: {{ .Values.port }}
    {{ end }}
      targetPort: {{ .Values.containerPort }}
      protocol: "TCP"
    
