apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.core.name }}
data:
  {{- range $key, $value := .Values.config.core.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}


