apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.job.name }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.config.core.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.config.job.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
