apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.config.core.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
