apiVersion: batch/v1
kind: Job
metadata:
  name: partitions-in-database
  namespace: {{ .Values.namespace }}
  labels:
    app: armonik
    service: partitions-in-database
    type: monitoring
spec:
  backoffLimit: 5
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: armonik
        job-name: partitions-in-database
        service: partitions-in-database
        type: monitoring
      name: partitions-in-database
    spec:
      automountServiceAccountToken: true
      containers:
      - name: job-partitions-in-database
        image: rtsp/mongosh:2.3.8
        imagePullPolicy: IfNotPresent
        command: ["mongosh"]
        args:
          - |
            -u $MongoDB__User -p $MongoDB__Password mongodb://$MongoDB__Host:$MongoDB__Port/database?authSource=$MongoDB__AuthSource --eval "db.PartitionData.drop()"
            -u $MongoDB__User -p $MongoDB__Password mongodb://$MongoDB__Host:$MongoDB__Port/database?authSource=$MongoDB__AuthSource --eval "db.PartitionData.insertMany([{'ParentPartitionIds':[],'PodConfiguration':null,'PodMax':100,'PodReserved':1,'PreemptionPercentage':50,'Priority':1,'_id':'bench'},{'ParentPartitionIds':[],'PodConfiguration':null,'PodMax':100,'PodReserved':1,'PreemptionPercentage':50,'Priority':1,'_id':'default'},{'ParentPartitionIds':[],'PodConfiguration':null,'PodMax':100,'PodReserved':1,'PreemptionPercentage':50,'Priority':1,'_id':'htcmock'},{'ParentPartitionIds':[],'PodConfiguration':null,'PodMax':100,'PodReserved':1,'PreemptionPercentage':50,'Priority':1,'_id':'stream'}])"
        env:
        - name: MongoDB__Password
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb
              optional: false
        - name: MongoDB__User
          value: root
        envFrom:
        - configMapRef:
            name: jobs-configmap
            optional: false
        - secretRef:
            name: activemq-crt
            optional: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: mongodb-crt
            mountPropagation: None
            mountPath: /mongodb/certs/
      dnsPolicy: ClusterFirst
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      enableServiceLinks: true
      restartPolicy: OnFailure
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
  {{- if .Values.tolerations }} 
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      - name: mongodb-crt
        secret:
          defaultMode: 420
          optional: false
          secretName: mongodb-crt