apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.log.name }}
  namespace: {{ .Values.namespace }}
data:
  Serilog__MinimumLevel: "{{ .Values.config.log.data.minimumLevel }}"
  {{- range $key, $value := .Values.config.log.data.overrides }}
  Serilog__MinimumLevel__Override__{{ $key }}: "{{ $value }}"
  {{- end }}
