{{ if .Values.metricsExporter.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: armonik
    service: metrics-exporter
    type: monitoring
  name: metrics-exporter
spec:
  selector:
    matchLabels:
      app: armonik
      service: metrics-exporter
      type: monitoring
  template:
    metadata:
      labels:
        app: armonik
        service: metrics-exporter
        type: monitoring
      name: metrics-exporter
    spec:
      automountServiceAccountToken: true
      containers:
      - image: {{ .Values.registry }}/armonik_control_metrics:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: metrics-exporter
        ports:
        - containerPort: 1080
          name: metrics
          protocol: TCP
        #terminationMessagePath: /dev/termination-log
        #terminationMessagePolicy: File
        #volumeMounts:
        # - name: mongodb
        #   mountPath: /mongodb/certs/
        #   readOnly: true
        env:
        - name: MongoDB__Password
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb
              optional: false
        envFrom:
        - configMapRef:
            name: core-configmap
            optional: false
        - configMapRef:
            name: log-configmap
            optional: false
        # - secretRef:
        #     name: activemq
        #     optional: false
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      volumes:
      - name: mongodb
        secret:
          secretName: mongodb-ca
          defaultMode: 420
  {{- if .Values.nodeSelector }}
      nodeSelector:
        service: metrics
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: service
        operator: Equal
        value: metrics
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: armonik
    service: metrics-exporter
    type: monitoring
  name: metrics-exporter
spec:
  selector:
    app: armonik
    service: metrics-exporter
    type: monitoring
  ports:
  - name: metrics-exporter
    port: 9419
    protocol: TCP
    targetPort: 1080
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: armonik
    service: metrics-exporter
    type: monitoring
  name: metrics-exporter-configmap
data:
  Host: "localhost"
  Port: "1080"
  Path: "/metrics"
{{ end }}