{{ if .Values.partitionMetricsExporter.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: armonik
    service: partition-metrics-exporter
    type: monitoring
  name: partition-metrics-exporter
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: armonik
      service: partition-metrics-exporter
      type: monitoring
  template:
    metadata:
      labels:
        app: armonik
        service: partition-metrics-exporter
        type: monitoring
      name: partition-metrics-exporter
      namespace: {{ .Values.namespace }}
    spec:
      automountServiceAccountToken: true
      containers:
      - image: {{ .Values.registry }}/armonik_control_partition_metrics:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: partition-metrics-exporter
        ports:
        - containerPort: 1080
          name: metrics
          protocol: TCP
        #terminationMessagePath: /dev/termination-log
        #terminationMessagePolicy: File
        volumeMounts:
        - name: mongodb
          mountPath: /mongodb/certs/
          readOnly: true
          #recursiveReadOnly: Disabled
        - name: mongodb-ca
          mountPath: /mongodb/certificate/
          readOnly: true
          #recursiveReadOnly: Disabled
        env:
        - name: MongoDB__Password
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb
              optional: false
        envFrom:
        - configMapRef:
            name: core-configmap
            optional: false
        - configMapRef:
            name: log-configmap
            optional: false
        # - secretRef:
        #     name: activemq
        #     optional: false
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      volumes:
      - name: mongodb
        secret:
          secretName: mongodb-crt
          defaultMode: 420
      - name: mongodb-ca
        secret:
          secretName: mongodb-crt
          defaultMode: 420
  {{ if .Values.nodeSelector }}
      nodeSelector:
        service: {{ .Values.nodeSelector }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: service
        operator: Equal
        value: metrics
  {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: armonik
    service: partition-metrics-exporter
    type: monitoring
  name: partition-metrics-exporter
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: armonik
    service: partition-metrics-exporter
    type: monitoring
  ports:
  - name: partition-metrics-exporter
    port: 9420
    protocol: TCP
    targetPort: 1080
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: armonik
    service: partition-metrics-exporter
    type: monitoring
  name: partition-metrics-exporter-configmap
  namespace: {{ .Values.global.namespace }}
data:
  Host: "localhost"
  Port: "1080"
  Path: "/metrics"
{{ end }}