apiVersion: v2
appVersion: 0.31.2
version: 0.1.0
name: armonik-control-plane
description: A Helm chart for Armonik
icon: https://25070129.fs1.hubspotusercontent-eu1.net/hubfs/25070129/Website/Images%20-%20Website/ArmoniK/logo_armonik_by_aneo%201.svg
kubeVersion: ">=v1.23.0-0"
keywords:
  - armonik
  - helm
type: application
home: https://github.com/aneoconsulting/ArmoniK
sources:
  - https://aneoconsulting.github.io/
maintainers:
  - name: Aneo
    email: armonik@aneo.fr
    url: armonik.fr

dependencies:
  - name: armonik-common
    version: 0.1.x
    repository: file://../armonik-common
