nameOverride: ""
imagePullSecrets: []
image: 
  registry: ""

grafanaDashboard:
  enable: true

global:
  imageRegistry: ""
  imagePullSecrets: []

environment:
  name: "local"
  description: "Armonik environment"

tls:
  type: "metrics-server"
  clusterDomain: cluster.local
  certManager:
    addInjectorAnnotations: true
    existingIssuer:
      # Use an existing cert-manager issuer
      enabled: false
      # Kind of the existing cert-manager issuer
      kind: "Issuer"
      # Name of the existing cert-manager issuer
      name: "my-issuer"
    # Set the requested duration (i.e. lifetime) of the Certificate.
    # See https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
    duration: ""
    # How long before the currently issued certificate’s expiry cert-manager should renew the certificate.
    # See https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
    renewBefore: ""
    # Add extra annotations to the Certificate resource
    annotations: {}
    # Add extra labels to the Certificate resource
    labels: {}

ingress:
  replicaCount: 1
  className: ""
  type: ClusterIP # LoadBalancer
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  repository: "nginxinc"
  image: "nginx-unprivileged"
  tag: "1.27.3"
  imagePullPolicy: IfNotPresent
  ports:
    grpc:
      name: ingress-grpc
      containerPort: 9080
      nodePortGrpc: 31669
      ServicePort: 5001
    http:
      name: ingress-http
      containerPort: 8080
      nodePortHttp: 32315
      ServicePort: 5000
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  volumes:
    #ingressSecret: ingress-crt
    mongodbSecret: mongodb
    #mongodbSecretCrt: mongodb-ca
    nginxConfigMap: ingress-nginx
    nginxStaticConfigMap: ingress-nginx-static

  tolerations:
  - effect: NoSchedule
    key: service
    operator: Equal
    value: control-plane
    
###########################################################
# Admin GUI
###########################################################
adminGui:
  name: admin-gui
  repository: dockerhubaneo
  image: "armonik_admin_app"
  tag: "0.13.3"
  imagePullPolicy: IfNotPresent
  port: 1080
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  tolerations:
  - effect: "NoSchedule"
    key: "service"
    operator: "Equal"
    value: "control-plane"

nodeSelector: {}

affinity: {}
