registry: dockerhubaneo
namespace: armonik
nameOverride: ""

ingress:
  replicaCount: 1
  className: ""
  type: ClusterIP
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  image: "nginxinc/nginx-unprivileged:1.27.3"
  imagePullPolicy: IfNotPresent
  ports:
    grpc:
      name: ingress-grpc
      containerPort: 9080
      nodePortGrpc: 31669
      ServicePort: 5001
    http:
      name: ingress-http
      containerPort: 8080
      nodePortHttp: 32315
      ServicePort: 5000
  
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  
  volumes:
    #ingressSecret: ingress-crt
    mongodbSecret: mongodb
    #mongodbSecretCrt: mongodb-ca
    nginxConfigMap: ingress-nginx
    nginxStaticConfigMap: ingress-nginx-static

  tolerations:
  - effect: NoSchedule
    key: service
    operator: Equal
    value: control-plane
    
###########################################################
# Admin GUI
###########################################################
adminGui:
  name: admin-gui
  image: "armonik_admin_app:0.13.3"
  imagePullPolicy: IfNotPresent
  port: 1080
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: 100m
      memory: 128Mi

  tolerations:
  - effect: "NoSchedule"
    key: "service"
    operator: "Equal"
    value: "control-plane"

nodeSelector: {}

affinity: {}
