resource "helm_release" "rabbitmq" {
  name       = var.name
  namespace  = var.namespace
  chart      = "rabbitmq"
  repository = var.helm_chart_repository
  version    = var.helm_chart_version
  values = [
    yamlencode({
      global = {
        security = {
          allowInsecureImages = true
        }
      }
      customStartupProbe = {
        exec = {
          command = [
            "rabbitmq-diagnostics",
            "check_port_connectivity"
          ]
        }

        initialDelaySeconds = 15
        periodSeconds       = 10
        timeoutSeconds      = 10
        successThreshold    = 1
        failureThreshold    = 5
      }
      customReadinessProbe = {
        exec = {
          command = [
            "rabbitmq-diagnostics",
            "check_port_connectivity"
          ]
        }

        initialDelaySeconds = 15
        periodSeconds       = 10
        timeoutSeconds      = 10
        successThreshold    = 1
        failureThreshold    = 5
      }
      customLivenessProbe = {
        exec = {
          command = [
            "rabbitmq-diagnostics",
            "check_port_connectivity"
          ]
        }

        initialDelaySeconds = 15
        periodSeconds       = 10
        timeoutSeconds      = 10
        successThreshold    = 1
        failureThreshold    = 5
      }

      auth = {
        tls = {
          enabled          = true
          sslOptionsVerify = "verify_none"
          failIfNoCert     = false
          autoGenerated    = true
          failIfNoPeerCert = false
        }

        username = random_string.mq_application_user.result
        password = random_password.mq_application_password.result
      }

      image = {
        repository = coalesce(var.image, "bitnamilegacy/rabbitmq")
        tag        = var.tag
      }

      volumePermissions = {
        image = {
          repository = "bitnamilegacy/os-shell"
        }
      }

      extraPlugins = "rabbitmq_amqp1_0"
    })
  ]
}
