apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app.kubernetes.io/name: database
  ports:
    - port: 27017
      targetPort: conn
  # type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app.kubernetes.io/name: database
spec:
  containers:
  - name: database
    image: mongo:7.0.5
    command:
      - mongod
      - --bind_ip_all
      - --replSet
      - repSet0
    ports:
      - containerPort: 27017
        name: conn

# kubectl exec database -- mongosh mongodb://localhost:27017/database --eval 'rs.initiate()'
# kubectl exec database -- mongosh mongodb://localhost:27017/database --eval 'db.PartitionData.insertOne({_id:"TestPartition0"})'
