apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.computePlaneConfigmaps.name }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.computePlaneConfigmaps.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  immutable: false

