apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.computePlaneConfigmaps.name }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.computePlaneConfigmaps.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  immutable: "false"
