apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.coreConfigmaps.name }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.coreConfigmaps.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}


