apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logConfigmaps.name }}
  namespace: {{ .Values.namespace }}
data:
  Serilog__MinimumLevel: {{ .Values.logConfigmaps.data.minimumLevel | quote}}
  {{- range $key, $value := .Values.logConfigmaps.data.overrides }}
  Serilog__MinimumLevel__Override__{{ $key }}: {{ $value | quote}}
  {{- end }}