apiVersion: v1
kind: Service
metadata:
  name: {{ include "computePlane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "computePlane.labels" . | nindent 4 }}
  {{- with .Values.service.labels -}}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.port.amqp }}
      protocol: TCP
      targetPort: amqp
    - name: dashboard
      port: {{ .Values.service.port.dashboard }}
      protocol: TCP
      targetPort: dashboard
  selector:
    {{- include "computePlane.selectorLabels" . | nindent 4 }}
