apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-configmap
  namespace: {{ .Values.namespace }}
data:
   {{- range $key, $value := .Values.workerConfigmaps.data }}
   {{ $key }}: {{ $value | quote }}
   {{- end }}

