{{- if .Values.workerConfigmaps.data -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "computePlane.labels" . | nindent 4 }}
data:
   {{- range $key, $value := .Values.workerConfigmaps.data }}
   {{ $key }}: {{ $value | quote }}
   {{- end }}
{{- end }}
