{{- $me := .Values.metricsExporter | default dict -}}
{{- $svc := $me.service | default dict -}}
{{- if $me.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "armonik.fullname" . | printf "%s-metrics-exporter" | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ include "armonik.namespace" . }}
  labels:
    app.kubernetes.io/component: metrics-exporter
    armonik.fr/deployment: {{ include "armonik.conf.source" . | quote }}
    {{- include "armonik.labels" . | nindent 4 }}
  {{- with coalesce $svc.annotations $me.annotations .Values.annotations}}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
spec:
{{- if eq $svc.serviceType "HeadLess" }}
  type: "ClusterIP"
  clusterIP: "None"
{{ else }}
  type: {{ $svc.serviceType | quote}}
  clusterIP: null
{{- end }}
  selector:
    app.kubernetes.io/component: metrics-exporter
    {{- include "armonik.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ $svc.name }}
    {{- if (eq $svc.serviceType "HeadLess") -}}
      {{ $firstPort := index $me.ports 0 }}
      port: {{ $firstPort.containerPort }}
    {{ else }}
      {{- range $svc.ports }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- end }}
      protocol: "TCP"
    {{- end }}
{{- end }}
