name: percona-mongodb
namespace: default

operator:
  image: percona/percona-server-mongodb-operator
  tag: ""
  nodeSelector: {}
  annotations: {}

cluster:
  image: percona/percona-server-mongodb
  tag: ""
  databaseName: database
  replicas: 1
  nodeSelector: {}
  annotations: {}

tls:
  selfManaged: true          # generate certs in an init Job or use cert-manager
  validityPeriodHours: 8760

resources:
  shards: {}
  configsvr: {}
  mongos: {}

sharding: null               # set to an object to enable sharding

persistence:
  shards:
    storageSize: 8Gi
    storageClassName: ""
    storageProvisioner: ""
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
  configsvr:
    storageSize: 3Gi
    storageClassName: ""
    storageProvisioner: ""
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer    

timeout: 600

# TODO: Check if I'm missing anything here
