apiVersion: v2
name: armonik-configuration
description: A Helm chart for ArmoniK
icon: https://25070129.fs1.hubspotusercontent-eu1.net/hubfs/25070129/Website/Images%20-%20Website/ArmoniK/logo_armonik_by_aneo%201.svg
kubeVersion: ">=v1.25.0-0"
keywords:
  - armonik
  - helm
type: application
version: 0.1.0
maintainers:
  - name: Aneo
    email: armonik@aneo.fr
    url: armonik.fr
dependencies:
  - name: armonik-common
    version: 0.1.x
    repository: file://../armonik-common
