{
 "title": "MongoDB monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Is MongoService up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used connections",
   "type": "gauge",
   "description": "The current number of connections to the MongoDB database in comparison with the available number of connections.\n\nNote: Unexpected changes in the current number of client connections can be due to errors on your application or driver. All the officially supported MongoDB drivers use pools of connections in order to efficiently re-use them. If the number of client connections is getting very high, it should be related to a rise in the number of real client requests in which case you can scale to support this increasing load. If this growth is not expected, it often indicates a driver or configuration issue.",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Connections" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mongodb_ss_connections{conn_type=\"available\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cursors",
   "type": "timeseries",
   "description": "Number of cursors currently opened by MongoDB for clients.\n\nNote: A gradual increase in the number of open cursors without a corresponding growth of traffic is often symptomatic of poorly indexed queries. It can also be the result of long running queries due to large result sets.",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(mongodb_ss_metrics_cursor_open) by(csr_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database assertions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(mongodb_ss_asserts{instance=\"$instance\"}[$__interval])) by (assert_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Uptime",
   "type": "stat",
   "description": "Mongodb Service Uptime ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_ss_uptime", "legendFormat": "__auto" }
   ]
  },
  { "title": "Throughput: Operation rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Insert OpRate",
   "type": "timeseries",
   "description": "The number of insert operations received per second by the mongod instance.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"insert\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Update OpRate",
   "type": "timeseries",
   "description": "The number of update operations received per second by the mongod instance.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"update\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Delete OpRate",
   "type": "timeseries",
   "description": "The number of delete operations received per second by the mongod instance.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"delete\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Operations per second",
   "type": "timeseries",
   "description": "The number of operations received per second by the mongod instance (doesn't include \"write\").",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"command\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput: Database operation queue (Resource saturation problems can be detected here)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Number of clients with reads in progress or queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "clients" } },
   "targets": [
    {
     "expr": "mongodb_ss_globalLock_activeClients_readers{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of clients with writes in progress or queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "clients" } },
   "targets": [
    {
     "expr": "mongodb_ss_globalLock_activeClients_writers{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total number of queued operations awaiting execution",
   "type": "timeseries",
   "description": "Note: Can confirm if operations are accumulating faster than they're being executed.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "operations" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_globalLock_currentQueue{instance=\"$instance\"}) by(count_type)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Operation latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Read latency over time",
   "type": "timeseries",
   "description": "The evolution of the read latency over specific collections as a function of time",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_collstats_latencyStats_reads_latency{collection=~\"TaskData|Result|SessionData\",instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Write latency over time",
   "type": "timeseries",
   "description": "The evolution of the write latency over specific collections as a function of time.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_collstats_latencyStats_writes_latency{collection=~\"TaskData|Result|SessionData\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Commands latency over time",
   "type": "timeseries",
   "description": "The evolution of the latency of running database commands over specific collections as a function of time.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_collstats_latencyStats_commands_latency{collection=~\"TaskData|Result|SessionData\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Transaction latency over time",
   "type": "timeseries",
   "description": "The evolution of the database transaction latency over specific collections as a function of time.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_collstats_latencyStats_transactions_latency{collection=~\"TaskData|Result|SessionData\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Documents scanned per second",
   "type": "timeseries",
   "description": "Number of documents scanned per second during queries and query-plan evaluation",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_metrics_queryExecutor_scannedObjects{instance=\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indices scanned per second",
   "type": "timeseries",
   "description": "Number of index items scanned per second during queries and query-plan evaluation",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_metrics_queryExecutor_scanned{instance=\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true
  },
  {
   "title": "Virtual memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_mem_virtual{instance=\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by the database process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_mem_resident{instance=\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of page faults",
   "type": "timeseries",
   "description": "Page faults indicate operations which required the MongoDB to fetch data from disk because it wasn’t available in active memory (“hard” page fault), or when the operation required in-memory page relocation (“soft” page fault). Requests which trigger page faults take more time to execute than requests that do not. Frequent page faults may indicate that your data set is too large for the allocated memory. However that’s not a big issue if the throughput remains healthy. Limited and occasional page faults do not necessarily indicate serious problems. In order to reduce the frequency of page faults, you can increase the size of your RAM or consider adding more shards to your deployments in order to better distribute incoming requests. Page faults can also be a sign of inefficient schema design, redundant or unnecessary indexes, or anything using available RAM unnecessarily.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "faults/sec" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_extra_info_page_faults{instance=\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of space taken by dirty data in the cache ",
   "type": "timeseries",
   "description": "Dirty data designates data in the cache that has been modified but not yet applied (flushed) to disk. Growing amounts of dirty data could represent a bottleneck where data isn’t being written to disk fast enough. Scaling out by adding more shard will help you reduce the amount of dirty data. Note that the amount of dirty data is expected to grow until the next checkpoint.\n\nShould monitor this along with the iostat/disk usage during the checkpointing period. It'll map to a spike in fsync.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache{instance=\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cache pages evicted",
   "type": "timeseries",
   "description": "Allows us to observe the second way of triggering checkpointing. \nWhen eviction_dirty_target or eviction_dirty_trigger reaches 5% and 20%, respectively. However, it’s not normal and only happens when there’s too much write activity beyond what the hardware can handle.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_oplog_stats_storageStats_wiredTiger_cache_modified_pages_evicted{instance=\"$instance\"} + mongodb_oplog_stats_storageStats_wiredTiger_cache_unmodified_pages_evicted{instance=\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_rs_members_id{member_state=\"PRIMARY\"}",
     "legendFormat": "{{member_state}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time",
   "type": "timeseries",
   "description": "This metric can show a correlation with the replication lag value.",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodb_rs_members_pingMs{instance=\"$instance\"}",
     "legendFormat": "{{member_state}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "timeseries",
   "description": "delay between a write operation on the primary and its copy to a secondary",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(mongodb_members_optimeDate{member_state=\"PRIMARY\"}) - sum(mongodb_members_optimeDate{member_state=\"SECONDARY\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "description": "This shows the time since the last election.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_electionCandidateMetrics_lastElectionDate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_rs_members_id{member_state=\"SECONDARY\", instance=\"$instance\"}",
     "legendFormat": "{{member_state}} - {{instance}}"
    }
   ]
  }
 ]
}