{
 "title": "Node disk monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "nodeNames",
    "label": "Database node names",
    "query": {
     "query": "label_values(kubernetes_pod_node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Reads per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{kubernetes_pod_node_name=~\"$nodeNames\"}[$__rate_interval]))",
     "legendFormat": "Node reads per second"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{kubernetes_pod_node_name=~\"$nodeNames\"}[$__rate_interval])) + sum(rate(node_disk_writes_completed_total{kubernetes_pod_node_name=~\"$nodeNames\"}[$__rate_interval]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Time spent per read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(node_disk_read_time_seconds_total[5m])) / sum(delta(node_disk_reads_completed_total[5m]))",
     "legendFormat": "Average time spent per read"
    }
   ]
  },
  {
   "title": "Data read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[$__rate_interval]))",
     "legendFormat": "Average bytes read"
    }
   ]
  },
  {
   "title": "Data read/write rate",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[$__rate_interval])) + sum(irate(node_disk_written_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{kubernetes_pod_node_name=~\"$nodeNames\"}[$__rate_interval]))",
     "legendFormat": "Node writes per second"
    }
   ]
  },
  {
   "title": "Time spent per write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "sum(delta(node_disk_write_time_seconds_total[5m])) / sum(delta(node_disk_writes_completed_total[5m]))",
     "legendFormat": "Average time spent per write"
    }
   ]
  },
  {
   "title": "Data write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[$__rate_interval]))",
     "legendFormat": "Average bytes written"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_pod_node_name=~\"$nodeNames\"} - node_memory_MemFree_bytes{kubernetes_pod_node_name=~\"$nodeNames\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_pod_node_name=~\"$nodeNames\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{kubernetes_pod_node_name=~\"$nodeNames\", mode!='idle'}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(node_cpu_usage_seconds_total{kubernetes_pod_node_name=~\"$nodeNames\", mode!='idle'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}