{
 "title": "Task Handler Analytics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "podName",
    "label": "Pod Name",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TaskHandler operation durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_AcquireTask_milliseconds_bucket{kubernetes_pod_name=~\"$podName\"}[$__rate_interval])))",
     "legendFormat": "Task Acquisition Duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_PreProcessing_milliseconds_bucket{kubernetes_pod_name=~\"$podName\"}[$__rate_interval]))) ",
     "legendFormat": "Task Pre-processing Duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_RequestExecution_milliseconds_bucket{kubernetes_pod_name=~\"$podName\"}[$__rate_interval]))) ",
     "legendFormat": "Task Execution Request Duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_ExecuteTask_milliseconds_bucket{kubernetes_pod_name=~\"$podName\"}[$__rate_interval])))",
     "legendFormat": "Task Execution Duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_PostProcessing_milliseconds_bucket{kubernetes_pod_name=~\"$podName\"}[$__rate_interval])))",
     "legendFormat": "Task Post-Processing Duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_DisposeAsync_milliseconds_bucket{kubernetes_pod_name=~\"$podName\"}[$__rate_interval])))",
     "legendFormat": "Task Dispose Duration"
    }
   ]
  },
  {
   "title": "Task Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(TaskHandler_ExecuteTask_Count_total{kubernetes_pod_name=~\"$podName\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recently executed tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(armonik_htcmock_tasks_submitted[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks dispatched",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "armonik_tasks_dispatched", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tasks processing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "armonik_tasks_processing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tasks Queued",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "armonik_tasks_queued", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tasks Submitted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "armonik_tasks_submitted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TaskHandler operation metrics (95th percentile)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Task Acquisition Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_AcquireTask_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Preprocessing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_PreProcessing_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Request Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_RequestExecution_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Execute Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_ExecuteTask_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Post-Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_PostProcessing_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Dispose Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(TaskHandler_DisposeAsync_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TaskHandler operation metrics by instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Task Acquisition Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,kubernetes_pod_name) (rate(TaskHandler_AcquireTask_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Preprocessing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, kubernetes_pod_name) (rate(TaskHandler_PreProcessing_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Request Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, kubernetes_pod_name) (rate(TaskHandler_RequestExecution_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Execute Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, kubernetes_pod_name) (rate(TaskHandler_ExecuteTask_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Post-Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, kubernetes_pod_name) (rate(TaskHandler_PostProcessing_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Dispose Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, kubernetes_pod_name) (rate(TaskHandler_DisposeAsync_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}