{
 "title": "Compute Plane Execution",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "podName",
    "label": "Pod Name",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sum Request Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (delta(TaskHandler_RequestExecution_milliseconds_sum{job=\"metrics-polling-agent\"}[1m])/ delta(uptime_Milliseconds_total{job=\"metrics-polling-agent\"}[1m]))"
    },
    {
     "expr": "count(TaskHandler_RequestExecution_milliseconds_sum{job=\"metrics-polling-agent\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",namespace=\"armonik\", pod=~\"$podName\"}[1m]))"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"armonik\", job=\"kubernetes-resource\", pod=~\"$podName\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "delta(TaskHandler_RequestExecution_milliseconds_sum{job=\"metrics-polling-agent\", kubernetes_pod_name=~\"$podName\"}[1m]) / delta(uptime_Milliseconds_total{job=\"metrics-polling-agent\", kubernetes_pod_name=~\"$podName\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{job=\"kubernetes-cadvisor\",namespace=\"armonik\", pod=~\"$podName\"})"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"armonik\", job=\"kubernetes-resource\", pod=~\"$podName\"}",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}