# ==== Environments ====
environments: 
  local:
    values:
      - values.yaml
  
  aws:
    values:
      - values-aws.yaml
  
  gcp:
    values:
      - values-gcp-bench.yaml
---
# ==== Helm defaults (optional) ====
helmDefaults:
  cleanupOnFail: false
  verify: false
  wait: false
  atomic: false
  skipDeps: true
  timeout: 120
  createNamespace: true

---
# ==== Releases ====
releases:
  - name: armonik
    chart: "."
    namespace: armonik
