{{- range .Values.subnets }}
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
    name: {{ .az | quote }}
spec:
    subnet: {{ .id | quote }}
    securityGroups:
    {{- range .sgs }}
    - {{ . | quote }}
    {{- end }}
{{- end }}  