apiVersion: v2
name: keda-hpa-activemq
description: A KEDA ScaledObject scaling one ArmoniK workload

kubeVersion: ">=v1.23.0-0"
type: application
version: 0.1.0
appVersion: "0.1.0"

home: https://github.com/aneoconsulting/ArmoniK.Infra/tree/main/charts/keda-hpa
sources:
  - https://github.com/aneoconsulting/ArmoniK.Infra

maintainers:
  - name: Aneo
    email: armonik-support@aneo.fr
    url: armonik.fr
