# Default values for keda-hpa-activemq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Suffix to add to the resource
suffix: ""

# -- Scale target reference
scaleTargetRef:
  # -- Kubernetes API version to be used
  apiVersion: "apps/v1"                                       # Optional. Default: apps/v1
  # -- Kid of the Kubernetes resource to be scaled
  kind: "Deployment"                                          # Optional. Default: Deployment
  # -- Name of the Kubernetes resource to be scaled
  name: ""                                                    # Mandatory. Must be in the same namespace as the ScaledObject
  # -- Name of the container to be scaled
  envSourceContainerName: ".spec.template.spec.containers[0]"   # Optional. Default: .spec.template.spec.containers[0]

# -- Polling interval in seconds
pollingInterval: 30                                          # Optional. Default: 30 seconds
# -- Cooldown period in seconds
cooldownPeriod: 300                                         # Optional. Default: 300 seconds
# -- Count of idle replicas
idleReplicaCount: 0                                           # Optional. Default: ignored, must be less than minReplicaCount
# -- Minimum count of replicas
minReplicaCount: 1                                           # Optional. Default: 0
# -- Maximum count of replicas
maxReplicaCount: 100                                         # Optional. Default: 100

# -- Fallback options
fallback:   # Optional. Section to specify fallback options
  # -- Threshold of failures
  failureThreshold: 3                                         # Mandatory if fallback section is included
  # -- Number of replicas
  replicas: 6                                                 # Mandatory if fallback section is included

# -- Advanced options to manage the behavior of the HPA
behavior:   # Optional. Section to specify advanced options
  # -- Restore to the original replicas count
  restoreToOriginalReplicaCount: false                        # Optional. Default: false
  # -- Stabilization window in seconds
  stabilizationWindowSeconds: 300
  # -- Type of the target
  type: Percent
  # -- Value of the target
  value: 100
  # -- Period in seconds
  periodSeconds: 15

# -- Triggers for HPA
triggers: []
