{{- if .Values.init.enabled }}
{{- $conf := list
    (include "armonik.control.init.confHelper" $ | fromYaml)
    .Values.conf
    .Values.init.conf
  | include "armonik.conf.merge" | fromYaml -}}
{{- $conf = list $conf $ | include "armonik.conf.resolve" | fromYaml -}}
{{- $image := list . "init.image" .Values.init.image .Values.image | include "armonik.utils.imageConf" | fromYaml }}
{{- $ctx := dict "root" $ "conf" $conf "image" $image -}}
{{- $podSpec := list (include "armonik.control.init.podSpec" $ctx) .Values.init.podSpecPatch "init.podSpecPatch" | include "armonik.utils.patch" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "armonik.fullname" . | printf "%s-init" | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ include "armonik.namespace" . }}
  labels:
    app.kubernetes.io/component: init
    app.kubernetes.io/part-of: control-plane
    {{- include "armonik.labels" . | nindent 4 }}
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 1
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: {{ include "armonik.fullname" . | printf "%s-init" | trunc 63 | trimSuffix "-" | quote }}
        app.kubernetes.io/component: init
        app.kubernetes.io/part-of: control-plane
        {{- include "armonik.labels" . | nindent 8 }}
        {{- with .Values.init.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      name: init
    spec: {{- $podSpec | nindent 6 }}
{{- end }}
