{{- if  list .Values "networkPolicy" "enabled" | include "armonik.utils.index" }}
{{- include "armonik.netpol.render" (dict
      "context" .
      "component" "fluent-bit"
      "config" (include "armonik.netpol.fluentBitEgress" . | fromYaml)
  ) }}
{{- end }}
