{{- $operatorSelector := dict
    "matchLabels" (dict
      "app.kubernetes.io/name" "mongodb-operator")
}}

{{- $serverSelector := dict
    "matchLabels" (dict
      "app.kubernetes.io/name" "percona-server-mongodb")
}}

{{- $dnsRule := include "armonik.netpol.dnsRule" dict | fromYaml }}
{{- $kubeApiRule := include "armonik.netpol.kubeApiRule" dict | fromYaml }}

{{- if and
      (list .Values "networkPolicy" "mongodb" "enabled" | include "armonik.utils.index" | default false)
      (list .Values "networkPolicy" "mongodb" "operator" "enabled" | include "armonik.utils.index" | default false)
}}

{{ include "armonik.netpol.render" (dict
  "context" $
  "component" "mongodb-operator"
  "config" (dict
    "podSelector" $operatorSelector
    "policyTypes" (list "Ingress" "Egress")
    "ingress" (dict
      "rules" (list
        (dict
          "from" (list
            (dict
              "namespaceSelector" (dict)
              "podSelector" $serverSelector
            )
          )
        )
      )
    )
    "egress" (dict
      "rules" (list
        (dict
          "to" (list
            (dict
              "namespaceSelector" (dict)
              "podSelector" $serverSelector
            )
            (dict
              "namespaceSelector" (dict)
              "podSelector" (dict
                "matchLabels" (dict
                  "app.kubernetes.io/name" "cert-manager"
                )
              )
            )
          )
          "ports" (list (dict "protocol" "TCP" "port" (include "armonik.mongodb.port" . | trim | int)))
        )
        $dnsRule
        $kubeApiRule
      )
    )
  )
) }}

{{- end }}
---
{{- if and
      (list .Values "networkPolicy" "mongodb" "enabled" | include "armonik.utils.index" | default false)
      (list .Values "networkPolicy" "mongodb" "server" "enabled" | include "armonik.utils.index" | default false)
}}


{{ include "armonik.netpol.render" (dict
  "context" $
  "component" "mongodb-server"
  "config" (dict
    "podSelector" $serverSelector
    "policyTypes" (list "Ingress" "Egress")
    "ingress" (dict
      "rules" (list
        (dict
          "from" (list
            (dict
              "namespaceSelector" (dict)
              "podSelector" $operatorSelector
            )
            (dict
              "namespaceSelector" (dict)
              "podSelector" (dict
                "matchLabels" (dict
                  "app.kubernetes.io/name" "control-plane"
                )
              )
            )
            (dict
              "namespaceSelector" (dict)
              "podSelector" (dict
                "matchLabels" (dict
                  "app.kubernetes.io/name" "compute-plane"
                )
              )
            )
          )
        )
      )
    )
    "egress" (dict
      "rules" (list
        (dict
          "to" (list
            (dict
              "namespaceSelector" (dict)
              "podSelector" $operatorSelector
            )
          )
        )
        $dnsRule
      )
    )
  )
) }}

{{- end }}
