Monitoring: [
  Submitter:GetServiceConfiguration,
  Submitter:CountTasks,
  Submitter:GetTaskStatus,
  Submitter:GetResultStatus,
  Submitter:ListTasks,
  Submitter:ListSessions,
  Sessions:GetSession,
  Sessions:ListSessions,
  Tasks:GetTask,
  Tasks:ListTasks,
  Tasks:GetResultIds,
  Tasks:CountTasksByStatus,
  Tasks:ListTasksDetailed,
  Results:GetOwnerTaskId,
  Results:ListResults,
  Results:GetServiceConfiguration,
  Results:GetResult,
  Applications:ListApplications,
  Events:GetEvents,
  Partitions:GetPartition,
  Partitions:ListPartitions,
  Versions:ListVersions,
  HealthChecks:CheckHealth
]