apiVersion: v1
kind: Service
metadata:
  labels:
    app: armonik
    service: admin-gui
  name: admin-gui
  namespace: {{ .Values.global.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: app-port
    port: 1080
    protocol: TCP
    targetPort: 1080
  selector:
    app: armonik
    service: admin-gui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
