apiVersion: v1
kind: Service
metadata:
  labels:
    app: armonik
    service: admin-gui
  name: admin-gui
  namespace: {{ .Values.global.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  {{- toYaml .Values.adminGui.service.servicePorts | nindent 2 }}
status:
  loadBalancer: {}
