apiVersion: v1
data:
  environment.json: '{"color": "#80ff80", "description": "{{ .Values.global.environment.description }}", "name": "{{ .Values.global.environment.name }}", "version": "{{ .Chart.AppVersion }}"}'
  gui_configuration: "{}"
immutable: false
kind: ConfigMap
metadata:
  name: ingress-nginx-static
