apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: armonik
    service: ingress
  name: ingress
  namespace: {{ .Values.global.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: armonik
      service: ingress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: armonik
        service: ingress
      name: ingress
      namespace: armonik
    spec:
      automountServiceAccountToken: true
      containers:
      - envFrom:
        - configMapRef:
            name: ingress-nginx
            optional: false
        image: nginxinc/nginx-unprivileged:1.27.0-alpine-slim
        imagePullPolicy: IfNotPresent
        name: ingress
        ports:
        - containerPort: 8080
          name: ingress-p-http
          protocol: TCP
        - containerPort: 9080
          name: ingress-p-grpc
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ingress
          mountPropagation: None
          name: ingress-secret-volume
          readOnly: true
        - mountPath: /ingressclient
          mountPropagation: None
          name: ingress-client-secret-volume
          readOnly: true
        - mountPath: /etc/nginx/conf.d
          mountPropagation: None
          name: ingress-nginx
          readOnly: true
        - mountPath: /static
          mountPropagation: None
          name: static
          readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      #nodeSelector:
      #  service: control-plane
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: service
        operator: Equal
        value: control-plane
      volumes:
      - name: ingress-secret-volume
        secret:
          defaultMode: 420
          optional: false
          secretName: ingress-server-certificates
      - name: ingress-client-secret-volume
        secret:
          defaultMode: 420
          optional: false
          secretName: ingress-user-certificate-authority
      - configMap:
          defaultMode: 420
          name: ingress-nginx
          optional: false
        name: ingress-nginx
      - configMap:
          defaultMode: 420
          name: ingress-nginx-static
          optional: false
        name: static
