apiVersion: v1
kind: Service
metadata:
  labels:
    app: armonik
    service: ingress
  name: ingress
  namespace: {{ .Values.global.namespace }}
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ingress-p-http
    nodePort: 32689
    port: 5000
    protocol: TCP
    targetPort: 8080
  - name: ingress-p-grpc
    nodePort: 30313
    port: 5001
    protocol: TCP
    targetPort: 9080
  selector:
    app: armonik
    service: ingress
  sessionAffinity: None
  type: LoadBalancer