{{- if .Values.ingress.enabled -}} {{/* TODO: Check this */}}
{{- $fullName := include "ingress.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- if .Values.global.namespace }} # use the global value if it is set,
    namespace: {{ .Values.global.namespace }}
  {{- else }} # else use local value
    namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
    app: {{/* TODO */}}
    service: {{/* TODO */}}
  {{- with .Values.ingress.annotations }} {{/* TODO // Check if there is annotations for ingress */}}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{/* TODO */}}
{{- end }}
