apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    service: ingress
  name: ingress
spec:
  {{ if eq .Values.ingress.type "LoadBalancer" }}
  externalTrafficPolicy: "Cluster"
  internalTrafficPolicy: "Cluster"
  allocateLoadBalancerNodePorts: true
  type: {{ .Values.ingress.type }}
  {{ end }}
  ports:
    - name: ingress-http
      nodePort: {{ .Values.ingress.ports.http.nodePortHttp }}
      port: {{ .Values.ingress.ports.http.ServicePort }}
      protocol: TCP
      targetPort: {{ .Values.ingress.ports.http.containerPort }}
    - name: ingress-grpc
      nodePort: {{ .Values.ingress.ports.grpc.nodePortGrpc }}
      port: {{ .Values.ingress.ports.grpc.ServicePort }}
      protocol: TCP
      targetPort: {{ .Values.ingress.ports.grpc.containerPort }}
  selector:
    app: {{ .Release.Name }}
    service: ingress
