{
 "title": "Compute Plane Execution",
 "tags": [ "ArmoniK" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "ArmoniK deployment",
    "query": {
     "query": "label_values(armonik_fr_deployment)"
    }
   },
   {
    "name": "podName",
    "label": "Pod Name",
    "query": {
     "query": "label_values(up{job=\"metrics-polling-agent\", armonik_fr_deployment=~\"$deployment\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": "worker-0 : worker-0,polling-agent : polling-agent"
   }
  ]
 },
 "panels": [
  {
   "title": "Sum Request Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (delta(TaskHandler_RequestExecution_milliseconds_sum{job=\"metrics-polling-agent\",armonik_fr_deployment=~\"$deployment\"}[1m])/ delta(uptime_Milliseconds_total{job=\"metrics-polling-agent\",armonik_fr_deployment=~\"$deployment\"}[1m]))",
     "legendFormat": "utilization"
    },
    {
     "expr": "count(TaskHandler_RequestExecution_milliseconds_sum{job=\"metrics-polling-agent\",armonik_fr_deployment=~\"$deployment\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "delta(TaskHandler_RequestExecution_milliseconds_sum{job=\"metrics-polling-agent\",armonik_fr_deployment=~\"$deployment\", pod=~\"$podName\"}[1m]) / delta(uptime_Milliseconds_total{job=\"metrics-polling-agent\",armonik_fr_deployment=~\"$deployment\", pod=~\"$podName\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_cpu_usage_seconds_total{job=\"kubelet\", pod=~\"$podName\"}[1m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{job=\"kubelet\", pod=~\"$podName\", container=~\"$container\"}[1m])",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{job=\"kubelet\", pod=~\"$podName\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"kubelet\", pod=~\"$podName\", container=~\"$container\"}",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  }
 ]
}