{
 "title": "Updated Node disk monitoring",
 "time": { "from": "2024-12-04T11:49:07.416Z", "to": "2024-12-04T12:36:15.346Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "description": "Rate of disk reads/writes for the database",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{service=\"state-database\"}[$__rate_interval])) + sum(rate(container_fs_writes_total{service=\"state-database\"}[$__rate_interval]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Reads per second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{service=\"state-database\"}[$__rate_interval]))",
     "legendFormat": "Node reads per second"
    }
   ]
  },
  {
   "title": "Writes per second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{service=\"state-database\"}[$__rate_interval]))",
     "legendFormat": "Node writes per second"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Database memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{service=\"state-database\"})",
     "legendFormat": "Current memory usage"
    },
    {
     "expr": "sum(container_memory_max_usage_bytes{service=\"state-database\"})",
     "legendFormat": "Max memory usage"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", service=\"state-database\"}[$interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent per read",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(delta(container_fs_read_seconds_total{service=\"state-database\"}[$interval])) / sum(delta(container_fs_reads_total{service=\"state-database\"}[$interval]))",
     "legendFormat": "Average time spent per read"
    }
   ]
  },
  {
   "title": "Time spent per write",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 38 },
   "targets": [
    {
     "expr": "sum(delta(container_fs_write_seconds_total{service=\"state-database\"}[$interval])) / sum(delta(container_fs_writes_total[$interval]))",
     "legendFormat": "Average time spent per write"
    }
   ]
  },
  {
   "title": "Data read rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{service=\"state-database\"}[$__rate_interval]))",
     "legendFormat": "Average bytes read"
    }
   ]
  },
  {
   "title": "Data write rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{service=\"state-database\"}[$__rate_interval]))",
     "legendFormat": "Average bytes written"
    }
   ]
  },
  {
   "title": "Data read/write rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{service=\"state-database\"}[$__rate_interval])) + sum(irate(container_fs_writes_bytes_total{service=\"state-database\"}[$__rate_interval]))",
     "legendFormat": "Read/Written bytes per second"
    }
   ]
  }
 ]
}