{
 "title": "ArmoniK at a glance",
 "tags": [ "ArmoniK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "ArmoniK deployment",
    "query": {
     "query": "label_values(armonik_fr_deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ArmoniK Metrics",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"armonik.*\",job=\"metrics-exporter\",armonik_fr_deployment=~\"$deployment\"}"
    }
   ]
  },
  {
   "title": "CPU utilisation / node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance,mode) (irate(node_cpu_seconds_total{mode='user'}[1m]))"
    },
    {
     "expr": "avg by (instance,mode) (irate(node_cpu_seconds_total{mode='system'}[1m]))"
    }
   ]
  },
  {
   "title": "CPU utilisation / node / cpu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance,cpu) (irate(node_cpu_seconds_total{mode!='idle'}[1m]))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes " },
    { "expr": "node_memory_MemTotal_bytes" },
    { "expr": "node_memory_Cached_bytes" },
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "IO disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_disk_io_time_seconds_total{}[1m]))"
    }
   ]
  },
  {
   "title": "Return codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (instance, code) (irate(apiserver_request_total{job=\"apiserver\"}[1m]))"
    }
   ]
  }
 ]
}