resource "helm_release" "mongodb" {
  name       = var.helm_release_name
  namespace  = var.namespace
  chart      = var.mongodb_helm_chart.name
  repository = var.mongodb_helm_chart.repository
  version    = var.mongodb_helm_chart.version

  values = [
    yamlencode({
      "labels"       = var.labels
      "replicaCount" = var.mongodb.replicas_number
      "nodeSelector" = var.mongodb.node_selector
      "tolerations" = var.mongodb.node_selector != {} ? [
        for index in range(0, length(local.node_selector_keys)) : {
          key   = local.node_selector_keys[index]
          value = local.node_selector_values[index]
        }
      ] : []
      "podLabels" = var.labels
      "image" = {
        "registry"    = var.mongodb.registry
        "repository"  = var.mongodb.image
        "tag"         = var.mongodb.tag
        "pullSecrets" = var.mongodb.image_pull_secrets
      }
      "architecture" = "replicaset"
      "tls" = {
        "enabled"       = "true"
        "autoGenerated" = "true"
      }
      "auth" = {
        "databases" = var.mongodb.databases_names
      }
      "extraFlags" = var.mTLSEnabled ? "" : "--tlsAllowConnectionsWithoutCertificates"
      "persistentVolumeClaimRetentionPolicy" = {
        "enabled"     = "true"
        "whenDeleted" = "Delete"
      }
    })
  ]

  set_sensitive {
    name  = "auth.rootUser"
    value = random_string.mongodb_admin_user.result
  }
  set_sensitive {
    name  = "auth.rootPassword"
    value = random_password.mongodb_admin_password.result
  }
  set_sensitive {
    name  = "auth.usernames[0]"
    value = random_string.mongodb_application_user.result
  }
  set_sensitive {
    name  = "auth.passwords[0]"
    value = random_password.mongodb_application_password.result
  }
}
