{{/*
This Secret contain the internal URLs used by ArmoniK
components.

The URLs can be explicitly configured through the ingress subchart values:
  - control_plane_url
  - grafana_url
  - seq_url

When an URL is not explicitly configured, the template generates the
corresponding in-cluster Kubernetes service URL.

The generated Secret contains:
  - control-plane: URL of the ArmoniK control plane, when enabled
  - grafana: URL of the Grafana service, when enabled
  - seq: URL of the Seq service, when enabled

The Secret is created in the namespace of the ingress subchart.
*/}}
{{- $domain := include "armonik.clusterDomain" . -}}
{{- $ingress := .Values.ingress | default dict -}}
{{- $cpPort := include "armonik.controlPlane.servicePort" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $ingress.urlsSecretName $ | default (printf "%s-urls" .Release.Name) | quote }}
  namespace: {{ $ingress.urlsSecretNamespace | default (include "armonik.namespace" .Subcharts.ingress) | quote }}
type: Opaque
data:
  {{- if list .Values "control-plane" "enabled" | include "armonik.utils.index" }}
  {{- $url := $ingress.control_plane_url | default "" -}}
  {{- if not $url }}
  {{- with index .Subcharts "control-plane" }}
  {{- $url = printf "%s-control-plane.%s.svc.%s:%d"
      (include "armonik.controlPlane.source" $)
      (include "armonik.namespace" .)
      $domain
      (int $cpPort) -}}
  {{- end }}
  {{- end }}
  {{- if $url }}
  control-plane: {{ $url | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- range $component := list "grafana" "seq" }}
  {{- if list $.Values "dependencies" $component "enabled" | include "armonik.utils.index" }}
  {{- $url := index $ingress (printf "%s_url" $component) | default "" -}}
  {{- with index $.Subcharts.dependencies.Subcharts $component }}
  {{- if not $url }}
  {{- $url = printf "http://%s.%s.svc.%s"
      $component
      (include "armonik.namespace" .)
      $domain -}}
  {{- end }}
  {{- end }}
  {{- if $url }}
  {{ $component }}: {{ $url | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
