{{- if (index .Values.dependencies "prometheus-mongodb-exporter" "enabled") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: armonik-mongodb-exporter-uri
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "armonik.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb-exporter
    app.kubernetes.io/part-of: armonik
type: Opaque
data:
  mongodb-uri: {{ include "armonik.mongodb-exporter-uri" . | b64enc | quote }}
{{- end }}

