{{- if $.Subcharts.ingress }}
apiVersion: v1
kind: Secret
metadata:
  name: armonik-namespaces
  namespace: {{ include "armonik.namespace" .Subcharts.ingress | quote }}
type: Opaque
stringData:
  {{- include "armonik.namespaces" . | nindent 2 }}
{{- end }}

