{{- $namespaces := include "armonik.namespaces" . | fromJson -}}

apiVersion: v1
kind: Secret
metadata:
  name: armonik-namespaces
  namespace: {{ include "armonik.namespace" .Subcharts.ingress }}
type: Opaque
stringData:
  {{- range $component, $namespace := $namespaces }}
  {{ $component }}: {{ $namespace | quote }}
  {{- end }}
