{{ if (include "armonik.dependencies" $ | fromYaml).kubePrometheus }}
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
data:
  prometheus-additional.yaml: {{ .Files.Get "static-confs/prometheus/config.yaml" | b64enc }}
{{ end }}
