{{/* Recommanded way of initializing users by the Valkey chart 
see https://github.com/valkey-io/valkey-helm/tree/main/valkey#existing-secret-recommended */}}
{{- if .Values.dependencies.redis.enabled }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "redis-users" }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-users
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if $existingSecret }}
  {{- /* if secrets already exists same password is used to avoid rotation on helm upgrade */}}
  default: {{ index $existingSecret.data "default" }}
  {{- else }}
  default: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
