apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "core-configmap" .Values.config.core.name }}
data:
  {{ include "armonik.queue" . }}
  {{ if .Values.config.core.data }}
  {{- range $key, $value := .Values.config.core.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- else }}
  #Amqp__AllowHostMismatch: "true"
  #Amqp__CaPath: /amqp/tls-combined.pem
  Amqp__MaxPriority: "10"
  #Amqp__MaxRetries: "5"
  Amqp__Port: "5672"
  Amqp__QueueStorage__LockRefreshExtension: "00:02:00"
  Amqp__QueueStorage__LockRefreshPeriodicity: "00:00:45"
  Amqp__QueueStorage__PollPeriodicity: "00:00:10"
  Amqp__Scheme: AMQP
  Amqp__Password: admin
  Amqp__User: admin
  Authenticator__RequireAuthentication: "false"
  Authenticator__RequireAuthorization: "false"
  # Components__ObjectStorageAdaptorSettings__ClassName: ArmoniK.Core.Adapters.Embed.ObjectBuilder
  # Components__ObjectStorageAdaptorSettings__AdapterAbsolutePath: /adapters/object/embed/ArmoniK.Core.Adapters.Embed.dll
  Components__ObjectStorageAdaptorSettings__ClassName: ArmoniK.Core.Adapters.Redis.ObjectBuilder
  Components__ObjectStorageAdaptorSettings__AdapterAbsolutePath: /adapters/object/redis/ArmoniK.Core.Adapters.Redis.dll
  Components__ObjectStorage: ArmoniK.Adapters.Redis.ObjectStorage
  Components__QueueAdaptorSettings__AdapterAbsolutePath: /adapters/queue/amqp/ArmoniK.Core.Adapters.Amqp.dll
  Components__QueueAdaptorSettings__ClassName: ArmoniK.Core.Adapters.Amqp.QueueBuilder
  Components__TableStorage: ArmoniK.Adapters.MongoDB.TableStorage
  MongoDB__User: root
  MongoDB__AllowInsecureTls: "true"
  MongoDB__AuthSource: admin
  #MongoDB__CAFile: /mongodb/certs/mongodb-ca-key
  MongoDB__DataRetention: 1.00:00:00
  MongoDB__DatabaseName: database
  MongoDB__DirectConnection: "true"
  MongoDB__Host: mongodb-headless
  MongoDB__Port: "27017"
  MongoDB__ReplicaSet: rs0
  #MongoDB__Sharding: "true"
  MongoDB__TableStorage__PollingDelay: "00:00:01"
  MongoDB__TableStorage__PollingDelayMax: "00:00:10"
  MongoDB__TableStorage__PollingDelayMin: "00:00:01"
  MongoDB__Tls: "false"
  Redis__User: ""
  #Redis__CaPath: /redis/ca.crt
  Redis__ClientName: ArmoniK.Core
  Redis__EndpointUrl: redis-master:6379
  #Redis__EndpointUrl: redis-headless:6379
  Redis__InstanceName: ArmoniKRedis
  Redis__Ssl: "false"
  #Redis__SslHost: 127.0.0.1
  Redis__Timeout: "30000"
  Redis__TtlTimeSpan: 1.00:00:00  
  {{- end }}
