{{ if .Values.global.dependencies.grafana }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-armonik
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
        isDefault: true
        uid: "PBFA97CFB590B2093"
        jsonData:
          tlsSkipVerify: true
        version: 1
{{ end }}
