apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "log-configmap" .Values.config.log.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    component: "log"
data:
  {{ if .Values.config.log.data }}
  Serilog__MinimumLevel: {{ .Values.config.log.data.minimumLevel | quote }}
  {{- range $key, $value := .Values.config.log.data.overrides }}
  Serilog__MinimumLevel__Override__{{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- else }}
  Serilog__MinimumLevel: Information
  Serilog__MinimumLevel__Override__ArmoniK.Core.Common.Auth.Authentication.Authenticator: Warning
  Serilog__MinimumLevel__Override__Grpc.AspNetCore.Server.ServerCallHandler: Warning
  Serilog__MinimumLevel__Override__Microsoft.AspNetCore.Authorization: Warning
  Serilog__MinimumLevel__Override__Microsoft.AspNetCore.Hosting.Diagnostics: Warning
  Serilog__MinimumLevel__Override__Microsoft.AspNetCore.Routing: Warning
  Serilog__MinimumLevel__Override__Microsoft.AspNetCore.Routing.EndpointMiddleware: Warning
  Serilog__MinimumLevel__Override__Microsoft.AspNetCore.Server.Kestrel: Warning
  Serilog__MinimumLevel__Override__Microsoft.Extensions.Diagnostics.HealthChecks: Warning
  Serilog__MinimumLevel__Override__Microsoft.Extensions.Http.DefaultHttpClientFactory: Warning
  Serilog__MinimumLevel__Override__Serilog.AspNetCore.RequestLoggingMiddleware: Warning
  {{- end }}
