name: TestMockV3
description: 'Test for mock v3 integrated worker'
inputs:
  control-plane-image:
    description: 'Repository/image for control plane docker image'
    required: false
    default: 'None'
  control-plane-tag:
    description: 'Tag for control plane docker image'
    required: false
    default: 'None'
  polling-agent-image:
    description: 'Repository/image for polling agent docker image'
    required: false
    default: 'None'
  polling-agent-tag:
    description: 'Tag for polling agent docker image'
    required: false
    default: 'None'
  version:
    description: 'ArmoniK repo version'
    required: false
    default: 'main'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.version }}
        submodules: true
        repository: aneoconsulting/ArmoniK

    - name: Install docker
      shell: bash
      run: |
        sh tools/install/docker.sh

    - name: Create HTC Mock V3 worker's docker image
      shell: bash
      run: |
        cd source/ArmoniK.Samples/Samples/HtcMockV3
        docker build -t dockerhubaneo/armonik_worker_htcmock:0.0.6 -f GridWorker/src/Dockerfile .

    - uses: ./
      name: Run local action
      id: deploy-infra
      with:
        worker-image: dockerhubaneo/armonik_worker_htcmock
        worker-tag: 0.0.6
        docker-is-installed: true
        control-plane-image: ${{ inputs.control-plane-image }}
        control-plane-tag: ${{ inputs.control-plane-tag }}
        polling-agent-image: ${{ inputs.polling-agent-image }}
        polling-agent-tag: ${{ inputs.polling-agent-tag }}

    - name: Test HTC Mock V3
      shell: bash
      run: |
        set -ex
        export CPIP=$(kubectl get svc control-plane -n armonik -o custom-columns="IP:.spec.clusterIP" --no-headers=true)
        export CPPort=$(kubectl get svc control-plane -n armonik -o custom-columns="PORT:.spec.ports[*].port" --no-headers=true)
        export Grpc__Endpoint=http://$CPIP:$CPPort

        cd source/ArmoniK.Samples/Samples/HtcMockV3/Client/src/
        dotnet build "ArmoniK.Samples.HtcMock.Client.csproj" -c Release
        dotnet bin/Release/net5.0/ArmoniK.Samples.HtcMock.Client.dll
