{{- $networkPolicyEnabled := list .Values "networkPolicy" "enabled"
    | include "armonik.utils.index"
    | default false
-}}

{{- if $networkPolicyEnabled }}

{{- include "armonik.netpol.render" (dict
      "context" .
      "component" "network-policy"
      "config" (include "armonik.netpol.computePlane" . | fromYaml)
  ) }}

{{- end }}
