{{- $fromComputePlane := dict
      "namespaceSelector" (dict)
      "podSelector" (dict "matchLabels" (dict "app.kubernetes.io/name" "compute-plane")) -}}

{{- $fromIngress := dict
      "namespaceSelector" (dict)
      "podSelector" (dict "matchLabels" (dict "app.kubernetes.io/name" "ingress")) -}}


{{- $fromAnyPod := dict "namespaceSelector" (dict) -}}

{{- $dnsEgress := list (include "armonik.netpol.dnsRule" dict | fromYaml) -}}

{{- if (list .Values "networkPolicy" "enabled" | include "armonik.utils.index" | default false) }}
{{- $workerCfg := dict
      "podSelector" (dict "matchLabels" (dict "app.kubernetes.io/name" "compute-plane"))
      "policyTypes" (list "Ingress" "Egress")
      "egress" (dict
        "rules" $dnsEgress
        "extraRules" (.Values.networkPolicy.extraEgressRules | default list)) -}}
{{ include "armonik.netpol.render" (dict "context" . "config" $workerCfg "component" "networkpolicy") }}
{{- end }}
