name: Helm charts linter
on:
  push:
    branches:
      - main
      - 0.2.x
  pull_request:
    branches:
      - main
      - 0.2.x
jobs:
  HelmChartlint:
    name: Lint Helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      # - name: "Upgrade Helm chart dependencies"
      #   id: deps-update
      #   uses: camptocamp/helm-dependency-update-action@v0.4.1
      #   with:
      #     chart-path: "charts/armonik"
      #     excluded-dependencies: "control-plane,compute-plane,ingress,activemq"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs charts/armonik --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --chart-dirs charts/armonik --target-branch ${{ github.event.repository.default_branch }} --chart-repos "bitnami=https://charts.bitnami.com/bitnami,cert-manager=https://charts.jetstack.io,seq=https://helm.datalust.co,grafana=https://grafana.github.io/helm-charts,keda=https://kedacore.github.io/charts"

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --chart-dirs charts/armonik --target-branch ${{ github.event.repository.default_branch }} --chart-repos "bitnami=https://charts.bitnami.com/bitnami,cert-manager=https://charts.jetstack.io,seq=https://helm.datalust.co,grafana=https://grafana.github.io/helm-charts,keda=https://kedacore.github.io/charts"
