name: Pre-commit
on:
  push:
    branches:
      - main
      - feat/revamp-helm
  pull_request:
    branches:
      - main
      - feat/revamp-helm
jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          terraform_version: latest
          
      - name: Configure Terraform cache dir
        run: |
          mkdir -p "$HOME/.terraform.d/plugin-cache"
          echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' > "$HOME/.terraformrc"

      - name: Install Terraform Linter
        uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef # v6
      
      - name: Install terraform-docs
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with: # Grab the latest version
          repo: terraform-docs/terraform-docs
          tag: v0.19.0
      
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
      
      - id: pre-commit
        name: Pre Commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Generate patch
        if: ${{ failure() && steps.pre-commit.conclusion == 'failure' }}
        run: |
          git diff > patch.diff

      - name: Upload Patch
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ failure() && steps.pre-commit.conclusion == 'failure' }}
        with:
          name: patch
          path: ./patch.diff

      - name: Apply Patch Instruction
        if: ${{ failure() && steps.pre-commit.conclusion == 'failure' }}
        run: |
          echo 'Run the command `pre-commit` or download the patch file at the following URL:'
          echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}${PR:+?pr=$PR}#artifacts"
        env:
          PR: ${{ github.event.pull_request.number }}
