{{- $ctx := dict "root" $ -}}
{{- $podSpec := list (include "activemq.podSpec" $ctx) .Values.podSpecPatch "podSpecPatch" | include "armonik.utils.patch" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "activemq.fullname" . }}
  namespace: {{ include "activemq.namespace" . | quote }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  {{- if not (has (quote .Values.revisionHistoryLimit) (list "" (quote ""))) }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "activemq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "activemq.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec: {{- $podSpec | nindent 6 }}
