{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:{{ include "armonik.fullname" . }}
  labels:
    {{- include "armonik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ template "armonik.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "activemq.serviceAccountName" . }}
    namespace: {{ include "armonik.namespace" . | quote }}
{{- end -}}
