{{- if .Values.healthCheckPolicy.enabled }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Values.healthCheckPolicy.name | default (printf "%s-health-check" (include "armonik.fullname" .)) }}
  namespace: {{ .Values.gateway.namespace | default (include "armonik.namespace" .) }}

  labels:
    app.kubernetes.io/component: healthcheckpolicy
    {{- include "armonik.labels" . | nindent 4 }}

  {{- with .Values.healthCheckPolicy.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  default:
    logConfig:
      enabled: {{ list .Values "healthCheckPolicy" "default" "logConfig" "enabled" | include "armonik.utils.index" | default true }}

    config:
      {{- $healthCheckType := list .Values "healthCheckPolicy" "default" "config" "type" | include "armonik.utils.index" | default "TCP" }}
      type: {{ $healthCheckType }}

      {{- if eq $healthCheckType "TCP" }}
      tcpHealthCheck:
        port: {{ list .Values "healthCheckPolicy" "default" "config" "tcpHealthCheck" "port" | include "armonik.utils.index" | default (include "armonik.ingress.containerPort" (dict "protocol" "grpc" "root" $)) }}
      {{- else if eq $healthCheckType "HTTP" }}
      httpHealthCheck:
        port: {{ list .Values "healthCheckPolicy" "default" "config" "httpHealthCheck" "port" | include "armonik.utils.index" | default (include "armonik.ingress.containerPort" (dict "protocol" "http" "root" $)) }}

        {{- with (list .Values "healthCheckPolicy" "default" "config" "httpHealthCheck" "requestPath" | include "armonik.utils.index") }}
        requestPath: {{ . | quote }}
        {{- end }}
      {{- end }}
  
  targetRef:
    group: ""
    kind: Service
    name: {{ list .Values "healthCheckPolicy" "targetRef" "name" | include "armonik.utils.index" | default (include "armonik.fullname" .) }}
    namespace: {{ list .Values "healthCheckPolicy" "targetRef" "namespace" | include "armonik.utils.index" | default (include "armonik.namespace" .) }}
{{- end }}
