{{- if and .Values.healthCheckPolicy.enabled (list .Values "networkPolicies" "healthCheck" "enabled" | include "armonik.utils.index" | default false) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "armonik.fullname" . }}-healthcheck
  namespace: {{ .Values.namespace | default (include "armonik.namespace" .) }}
  labels:
    app.kubernetes.io/component: ingress
    {{- include "armonik.labels" . | nindent 4 }}
spec:
  podSelector:
    {{- toYaml .Values.networkPolicies.healthCheck.podSelector | nindent 4 }}

  policyTypes:
    - Ingress

  ingress:
    - from:
        {{- toYaml .Values.networkPolicies.healthCheck.from | nindent 8 }}
      ports:
        {{- toYaml .Values.networkPolicies.healthCheck.ports | nindent 8 }}
{{- end }}